# print("Hello World", end=' and ')
# print("Hello Python!")
print("Hello World! Hello Python!")
print()
print("Hello World! \nHello Python!")
print()
print("Hello World! \rHello Python!")
print()
print("Hello World!\n\tHello Python!")
print()
print("Hello World!\b\b Hello Python!")
